parameters:
    simple_paginator_adapter_factory.class:  Frcho\SimplePaginatorBundle\Paginator\Adapter\AdapterFactory
    simple_paginator.class:  Frcho\SimplePaginatorBundle\Paginator\Paginator
    
services:
    frcho.simple_paginator.adapter_factory:
        class: '%simple_paginator_adapter_factory.class%'
        public: true       
        
    frcho.simple_paginator:
        class: '%simple_paginator.class%'
        public: true             
        arguments: [ "@request_stack", "@frcho.simple_paginator.adapter_factory" ]