parameters:
    templating.helper.simple_paginator.class:  Frcho\SimplePaginatorBundle\Templating\Helper\PaginatorHelper
    
services:
    templating.helper.frcho.simple_paginator:
        class: '%templating.helper.simple_paginator.class%'
        public: true 
        arguments: [ "@service_container" ]
        tags:
            - { name: 'templating.helper', alias: 'simple_paginator_helper' }           
          
